server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /leyou
    username: leyou
    password: leyou
    host: 192.168.0.4

leyou:
  sms:
    accessKeyId: LTAI4FuTpX83CSb1E7YBqrAh
    accessKeySecret: aonQQbq7GJUqAX9DUCQgHQ7WughCt6
    signName: 乐优商城
    verifyCodeTemplate: SMS_186616154
