server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    virtual-host: /leyou
    username: leyou
    password: leyou
    host: 192.168.0.4

leyou:
  sms:
    accessKeyId: LTAI4FqFQ1bwLuag3HvwzhMr
    accessKeySecret: 43Gbv3l3w8SwOasDchncOQhGwDgjoA
    signName: 乐优商城
    verifyCodeTemplate: SMS_186616154
